name: Create Release PR
on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        description: "The release type"
        type: choice
        options:
          - release
          - hotfix
      version:
        required: true
        description: "The release version X.Y.Z"
        type: string
  push:
    branches:
      - release/**
      - hotfix/**
jobs:
  config_maven:
    name: Maven Configuration
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit
  status:
    uses: wakamiti/wakamiti-github-actions/.github/workflows/status.yml@main
    secrets: inherit
    needs: [config_maven]
    with:
      branch: ${{ github.event_name == 'workflow_dispatch' 
        && format('{0}/{1}', github.event.inputs.type, 
          startsWith(github.event.inputs.version, 'v') && github.event.inputs.version || 
          format('v{0}', github.event.inputs.version)) 
        || github.ref_name }}
